export const ERR = {
  UNAUTHORIZED_ACCESS: 'Unauthorized access',
  CANNOT_CONNECT_SELF: 'Cannot connect with yourself',
  CONNECTION_EXISTS: 'Connection request already exists or is established',
  CONNECTION_NOT_FOUND: 'Connection not found',
  CONNECTION_NOT_ACCEPTED: 'Connection is not accepted',
  NOT_PART_OF_CONNECTION: 'You are not part of this connection',
  REQUEST_NOT_FOUND: 'Connection request not found',
  REQUEST_NOT_PENDING: 'This connection request is not pending',
  NOT_RECEIVER_OF_REQUEST: 'You are not the receiver of this connection request',
  NOTIFICATION_NOT_FOUND: 'Notification not found',
  FAILED_TO_CREATE_CONNECTION: 'Failed to create connection request',
  FAILED_TO_RESPOND_CONNECTION: 'Failed to respond to connection',
  FAILED_TO_LIST_CONNECTIONS: 'Failed to list connections',
  FAILED_TO_SEND_MESSAGE: 'Failed to send chat message',
  FAILED_TO_FETCH_HISTORY: 'Failed to fetch chat history',
  FAILED_TO_FETCH_NOTIFICATIONS: 'Failed to fetch notifications',
  FAILED_TO_MARK_NOTIFICATION: 'Failed to mark notification as read',
};
